name: Build project
on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: mymindstorm/setup-emsdk@v14
      - name: Install thirdparty libraries
        run: ./thirdparty/external_libs/build_dependencies.sh
      - name: Generate project
        run: emcmake cmkae -Bbuild
      - name: Build project
        run: cmake --build build
