name: Build project
on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: mymindstorm/setup-emsdk@v14
      - name: Test 1
        run: ls -la ../
      - name: Install thirdparty libraries
        run: ./thirdparty/external_libs/build_dependencies.sh
      - name: Generate project
        run: emcmake cmkae -Bbuild
      - name: Build project
        run: cmake --build build
